### ISSUE TITLE
1.7.10 boss bar is not supported

### ISSUE THREAD

**Issue by kangarko** [KyoriPowered/adventure-platform#182]
I would like to remove [our own implementation of legacy Boss bar](https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/remain/internal/BossBarInternals.java) in favor of Foundation but it's currently broken.

Code:

````java
audience.showBossBar(BossBar.bossBar(
				Component.text("Test"),
				1F, Color.WHITE, Overlay.PROGRESS));
````

Stack trace:

````
18:40:09 INFO]: java.lang.NoSuchMethodError: org.bukkit.entity.Entity.setCustomName(Ljava/lang/String;)V
[18:40:09 INFO]: 	at net.kyori.adventure.platform.bukkit.CraftBukkitFacet$FakeEntity.name(CraftBukkitFacet.java:1372)
[18:40:09 INFO]: 	at net.kyori.adventure.platform.facet.Facet$BossBarEntity.bossBarNameChanged(Facet.java:687)
[18:40:09 INFO]: 	at net.kyori.adventure.platform.facet.Facet$BossBar.bossBarInitialized(Facet.java:525)
[18:40:09 INFO]: 	at net.kyori.adventure.platform.bukkit.CraftBukkitFacet$BossBarWither.bossBarInitialized(CraftBukkitFacet.java:1408)
[18:40:09 INFO]: 	at net.kyori.adventure.platform.facet.FacetBossBarListener.bossBarInitialized(FacetBossBarListener.java:43)
[18:40:09 INFO]: 	at net.kyori.adventure.platform.facet.FacetAudience.showBossBar(FacetAudience.java:413)
[18:40:09 INFO]: 	at net.kyori.adventure.platform.bukkit.BukkitAudience.showBossBar(BukkitAudience.java:107)
````

Thank you!

**Comment by mbax** [comment]
Pull requests are welcomed!

Happy 10th birthday, 1.7.10 🥳

**Comment by kangarko** [comment]
Happy birthday also! 

Just found out that even using sendMessage() is broken. This can easily be fixed by only trying to look for the two constructors in the image below in the CraftBukkitFacet class on modern Minecraft versions.

I am unfamiliar with Adventure, I applied a dirty fix with my own library:

![a](https://i.imgur.com/kyV2IJJ.png)

If you have a hot minute, could you please edit the class using your knowledge?

The second issue is that even after the fix, the \n in Component.text("hello\nworld") are not properly recognized. This is because 1.7.10 needs one component per \n and client does not divide them.

![a](https://i.imgur.com/NS5qfQV.png)

Assuming there is a method to split components in Adventure, if someone is knowledgeable enough the pull request should not be too big. Thank you.
