### ISSUE TITLE
1.16.5 can't start: java.lang.NoSuchMethodError: net.kyori.adventure.platform.facet.FacetAudience.getOrDefault

### ISSUE THREAD

**Issue by kangarko** [KyoriPowered/adventure-platform#184]
````
[06:59:13 INFO]: java.lang.NoSuchMethodError: net.kyori.adventure.platform.facet.FacetAudience.getOrDefault(Lnet/kyori/adventure/pointer/Pointer;Ljava/lang/Object;)Ljava/lang/Object;
[06:59:13 INFO]: 	at net.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:113)
[06:59:13 INFO]: 	at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:99)
[06:59:13 INFO]: 	at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:171)
[06:59:13 INFO]: 	at java.util.HashMap.computeIfAbsent(HashMap.java:1128)
[06:59:13 INFO]: 	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2674)
[06:59:13 INFO]: 	at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:169)
[06:59:13 INFO]: 	at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89)
[06:59:13 INFO]: 	at net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53)
[06:59:13 INFO]: 	at org.mineacademy.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:316)
[06:59:13 INFO]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[06:59:13 INFO]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[06:59:13 INFO]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
````

**Comment by zml2008** [comment]
Looks like some sort of version mismatch in your build setup.

**Comment by kangarko** [comment]
Can you elaborate please? I just decompiled 1.16, the Audience does not implement Pointered where this method exists and is being called by adventure-platform.

**Comment by zml2008** [comment]
https://docs.advntr.dev/faq.html#why-am-i-getting-a-nosuchfielderror-nosuchmethoderror-classnotfoundexception-or-similar-when-updating-using-adventure-platform-adventure-text-minimessage-adventure-api-or-other-related-libraries-tools

**Comment by kangarko** [comment]
Are you suggesting I shade an older adventure-platform version for 1.16.5? Can't you just update the current version to not call Pointered#getOrDefault on legacy versions?

**Comment by zml2008** [comment]
adventure-platform needs a relocated version of adventure, it doesn't integrate with any platform-native instance of adventure that may exist.

**Comment by kangarko** [comment]
Thank you, makes sense now!

**Comment by HyperfireRS** [comment]
How did you fix this?

**Comment by kangarko** [comment]
I fixed this by using libby, which is a library for importing libraries on legacy minecraft versions, and I conditionally load different versions of adventure for legacy versions and then use reflection to call compatible methods. 

You can see an example of this here:

https://github.com/kangarko/Foundation/blob/v7/src/main/java/org/mineacademy/fo/plugin/SimplePlugin.java#L235
