### ISSUE TITLE
java.lang.NoSuchFieldError: LOCALE

### ISSUE THREAD

**Issue by cyberpwnn** [KyoriPowered/adventure-platform#60]
```java
// JavaPlugin onEnable()
BukkitAudiences.create(this);
```

```
java.lang.NoSuchFieldError: LOCALE
        at net.kyori.adventure.platform.bukkit.BukkitAudience.contributePointers(BukkitAudience.java:117) ~[?:?]
        at net.kyori.adventure.platform.facet.FacetAudience.pointers(FacetAudience.java:449) ~[?:?]
        at net.kyori.adventure.pointer.Pointered.getOrDefault(Pointered.java:65) ~[patched_1.17.1.jar:git-Purpur-1272]
        at net.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:114) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:99) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:162) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
        at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2722) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:162) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:88) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
```

**Comment by kezz** [comment]
You need to ensure you are using adventure-api 4.9.x.

**Comment by cyberpwnn** [comment]
> You need to ensure you are using adventure-api 4.9.x.

I was using 4.9.0. Upgrading to the latest (4.9.1) still causes the problem. I'm using these dependencies

```groovy
implementation "net.kyori:adventure-text-minimessage:4.2.0-SNAPSHOT"
implementation "net.kyori:adventure-platform-bukkit:4.0.0-SNAPSHOT"
implementation 'net.kyori:adventure-api:4.9.1'
```
