### ISSUE TITLE
java.lang.NoSuchFieldError: LOCALE

### ISSUE THREAD

**Issue by NextdoorPsycho** [KyoriPowered/adventure-platform#62]
```
// JavaPlugin onEnable()
BukkitAudiences.create(this);
java.lang.NoSuchFieldError: LOCALE
        at net.kyori.adventure.platform.bukkit.BukkitAudience.contributePointers(BukkitAudience.java:117) ~[?:?]
        at net.kyori.adventure.platform.facet.FacetAudience.pointers(FacetAudience.java:449) ~[?:?]
        at net.kyori.adventure.pointer.Pointered.getOrDefault(Pointered.java:65) ~[patched_1.17.1.jar:git-Purpur-1272]
        at net.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:114) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:99) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:162) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
        at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2722) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:162) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:88) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
        
```
Saw that issue, Still a problem tho
I was also using 4.9.0. Upgrading to the latest (4.9.1) and like the other post it still causes the problems

Issue https://github.com/KyoriPowered/adventure-platform/issues/60
This is more of a plea to look at the other issue if you can, or just close this one too but i would like to know how to resolve this

**Comment by zml2008** [comment]
not a bug, learn to manage dependencies

**Comment by kezz** [comment]
See #60 and #61.
