### ISSUE TITLE
NoSuchFieldError: LOCALE on Spigot 1.19 when calling BukkitAudiences#create(Plugin)

### ISSUE THREAD

**Issue by WasabiThumb** [KyoriPowered/adventure-platform#96]
Apologies if I'm missing something obvious because this is the first time I've used this library.

```
java.lang.NoSuchFieldError: LOCALE
        at net.kyori.adventure.platform.bukkit.BukkitAudience.contributePointers(BukkitAudience.java:117) ~[?:?]
        at net.kyori.adventure.platform.facet.FacetAudience.pointers(FacetAudience.java:453) ~[?:?]
        at net.kyori.adventure.pointer.Pointered.getOrDefault(Pointered.java:65) ~[?:?]
        at net.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:113) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:99) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:175) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:173) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
```

Server is running CraftBukkit version 3539-Spigot-56be6a8-82f7574 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)
Output of ``java --version``
```
openjdk 18.0.1.1 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2, mixed mode)
```
OS is Arch Linux x64

**Comment by KingOfSquares** [comment]
Is it properly shaded? Copying the standard response from Discord:

Why am I getting a NoSuchFieldError, NoSuchMethodError, ClassNotFoundException or similar when updating/using adventure-platform-*, adventure-text-minimessage, adventure-api or other related libraries/tools?

You need to ensure that you are properly shading and relocating your dependencies. Issues like this can be caused by:

- Not shading the correct version of adventure-api. You can check your dependency tree to see what or why your build tool is not including the correct version of the API that matches the one used by the platform version you are using.
- Not relocating your dependencies. If you are running on a platform that includes an older version of the API, or another mod/plugin is also not properly relocating their dependencies, you will use their out-of-date version of the API, causing errors.
- Building/running against a native implementation of adventure-api.  If you are running on a platform that includes an older version of the API, this could cause issues if the library depends on newer features that are not available in the outdated version of the API, your library will not be able to find these methods, causing errors.
- Relocating adventure-api and trying to use native/library methods. If you relocate the API, you will not be able to use any methods that the API in native implementations or libraries as method signatures will differ. Either shade and relocate this software, or do not use native methods. Alternatively, if you are shading and relocating a library but want to use the the API, make sure you are only relocating the packages that you are shading.

Please consult the documentation for your build tool for more information on how to shade, relocate and manage your dependencies.

**Comment by kezz** [comment]
The above message is correct, this is a build issue. For more support you can jump into our discord #off-topic channel or consult your build tool docs!
